services:
  backend:
    image: your_backend_image
    environment:
      - FASTAPI_SECRET_KEY
      - FASTAPI_HASH_ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES
      - USER_DB_URL
      - FILE_DB_URL
    ports:
      - "8000:8000"

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: your_frontend_image
    environment:
      - NEXT_PUBLIC_ENVIRONMENT
      - NEXT_PUBLIC_API_URL
    ports:
      - "3000:3000"

volumes:
  postgres_data:

