services:
  backend:
    build:
      context: ./backend-app/
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "8000:8000"
    depends_on:
      - userdb
      - filedb
    env_file:
      - backend.env

  frontend:
    build:
      context: ./frontend-app/
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - frontend.env

  userdb:
    image: postgres:13
    volumes:
      - userdb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network
    env_file:
      - database.env
  filedb:
    image: postgres:13
    volumes:
      - filedb_data:/var/lib/postgresql/data
    ports:
      - "4321:4321"
    networks:
      - my_network
    env_file:
      - database.env

volumes:
  userdb_data:
  filedb_data:

networks:
  my_network:
    driver: bridge
