FROM python:3.12-slim

# Update and install dependencies
RUN apt-get update \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

COPY /app/ /app/

ENV FASTAPI_HASH_ALGORITHM=HS256
ENV ACCESS_TOKEN_EXPIRE_MINUTES=30
ENV USER_DB_URL=sqlite:///./sql_app.db
ENV FILE_DB_URL=sqlite:///./file_sql.db

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
