FROM python:3.12-slim AS builder

# Update and install dependencies
RUN apt-get update \
	&& apt install sqlite3 \
	&& rm -rf /var/lib/apt/lists/*

RUN pip install poetry==1.8.3

ENV POETRY_NO_INTERACTION=1 \
	POETRY_VIRTUALENVS_IN_PROJECT=1 \
	POETRY_VIRTUALENVS_CREATE=1 \
	POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /

COPY pyproject.toml poetry.lock ./
RUN touch README.md

RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry install --no-root

FROM python:3.12-slim
ENV VIRTUAL_ENV=/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY  --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

COPY /app/ /app/

ENV FASTAPI_HASH_ALGORITHM=HS256
ENV ACCESS_TOKEN_EXPIRE_MINUTES=30
ENV USER_DB_URL=sqlite:///./sql_app.db
ENV FILE_DB_URL=sqlite:///./file_sql.db

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
